### ISSUE TITLE
Standalone Docker Container

### ISSUE THREAD

**Issue by FWeinb** [EverythingSmartHome/everything-presence-addons#1]
I see this was just released and this request might be out of scope of this project but would it be possible to publish the docker container to a registry so it can be used in a custom docker-compose HA setup.

**Comment by sdemmery** [comment]
Yeah same request for me, Im running HA on a sinology NAS dockerised so no access to aeons via the normal way. I can just about stand up my containers (after 3 years of running it like this :-) But creating an image form a repo is a bit beyond me. Maybe GPT might help me. Ha

**Comment by sdemmery** [comment]
Well to answer my own comment, I got this running in docker on my gas with the help of ChatGPT it was realticly easy & the web page loads. However I don't see any devices in the drop down. suspect this is because of these lines in the backend.py file? 

SUPERVISOR_TOKEN = os.getenv('SUPERVISOR_TOKEN')

HOME_ASSISTANT_API = 'http://supervisor/core/api'

I suppose i will have to have a long lived API token set up & then that API address will be wrong. Any thoughts anyone, Ive tired simply replacing the address with my local HA ip but no luck. Little beyond me this, but will keep going.

**Comment by SicSo** [comment]
https://developers.home-assistant.io/docs/api/rest/

I don't know if this helps or not.

**Comment by EverythingSmartHome** [comment]
It was actually easier than I thought it was going to be :D

Added in https://github.com/EverythingSmartHome/everything-presence-addons/pull/4

If you'd like to try it while I figure it out how to publish a docker image:

1. Download everything-presence-mmwave-configurator folder
2. Run  `docker build -t everything-presence_mmwave_configurator:latest .`
3. Run `docker run -d -e HA_URL=http://HA_URL:8123 -e HA_TOKEN=LONG_LIVE_TOKEN -p 8099:8099 --name everything-presence-mmwave-configurator everything_presence_mmwave_configurator:latest
`

**Comment by EverythingSmartHome** [comment]
Never mind, got it added to Docker Hub.

So now all you need to do is:

`docker run -d -e HA_URL=http://HA_URL:8123 -e HA_TOKEN=LONG_LIVE_TOKEN -p 8099:8099 --name everything-presence-mmwave-configurator everything-presence-mmwave-configurator:latest `

Would appreciate feedback

**Comment by EverythingSmartHome** [comment]
Oh my bad, typo. Should be this:

```
docker run -d -e HA_URL=http://HA_URL:8123 -e HA_TOKEN=LONG_LIVE_TOKEN -p 8099:8099 everythingsmarthome/everything-presence-mmwave-configurator:latest
```

**Comment by sdemmery** [comment]
@EverythingSmartHome You are the Man! Working perfectly for me. Should work for anyone running docker if it works for me. to recap I am running docker on synology. Instead of using the container manager as we would normally (although give the parms above you can do that too now) I just ssh to the box & ran the command above replacing the HA_URL with my local IP & then replaced the LONG_LIVE_TOKEN with one I generated under the security table of profile in HA

Great work, loving my first of many lite sensors

**Comment by SicSo** [comment]
Adding this for completion, if the interface is on a different port from 8123, that should be reflected in the URL.

**Comment by EverythingSmartHome** [comment]
Glad to hear it! I'll close this as completed in that case as I've tested on a few docker installs myself and seems to be good.
